Repository focus-shift/jollyday, pull requests merged in 2023-10, with the labels that each got.

#342 Fix British Overseas Territories
  jollyday-core/src/main/resources/holidays/Holidays_bm.xml
  jollyday-core/src/main/resources/holidays/Holidays_ky.xml
  jollyday-core/src/main/resources/holidays/Holidays_vg.xml
  jollyday-tests/src/test/java/de/focus_shift/jollyday/tests/country/HolidayBMTest.java
  jollyday-tests/src/test/resources/holidays/Holidays_test_bm_2015.xml
  jollyday-tests/src/test/resources/holidays/Holidays_test_bm_2016.xml
Labels: type: enhancement, country: virgin islands (british), country: cayman islands, country: bermuda

#315 Update build matrix to build with java 21 early access builds
  .github/workflows/build.yml
  pom.xml
Labels: type: enhancement

#354 Fix typos
  jollyday-core/src/main/java/de/focus_shift/jollyday/core/parser/predicates/ValidCycle.java
  jollyday-core/src/main/resources/descriptions/holiday_descriptions_de.properties
Labels: type: bug, country: germany, topic: i18n
