Repository focus-shift/jollyday, pull requests merged in 2024-12, with the labels that each got.

#586 XML unmarshal: performance improvements - static XMLUtil with static converters
  jollyday-jackson/src/main/java/de/focus_shift/jollyday/jackson/JacksonConfigurationService.java
  jollyday-jackson/src/main/java/de/focus_shift/jollyday/jackson/XMLUtil.java
  jollyday-jackson/src/test/java/de/focus_shift/jollyday/jackson/test/XMLUtilTest.java
  jollyday-jaxb/src/main/java/de/focus_shift/jollyday/jaxb/JaxbConfigurationService.java
  jollyday-jaxb/src/main/java/de/focus_shift/jollyday/jaxb/XMLUtil.java
  jollyday-jaxb/src/test/java/de/focus_shift/jollyday/jaxb/test/XMLUtilTest.java
Labels: type: enhancement, topic: performance

#665 Switzerland - Mauritius Day missing in Appenzell Innerrhoden
  jollyday-core/src/main/resources/descriptions/holiday_descriptions.properties
  jollyday-core/src/main/resources/descriptions/holiday_descriptions_de.properties
  jollyday-core/src/main/resources/descriptions/holiday_descriptions_el.properties
  jollyday-core/src/main/resources/descriptions/holiday_descriptions_fr.properties
  jollyday-core/src/main/resources/descriptions/holiday_descriptions_nl.properties
  jollyday-core/src/main/resources/descriptions/holiday_descriptions_pt.properties
  jollyday-core/src/main/resources/descriptions/holiday_descriptions_sv.properties
  jollyday-core/src/main/resources/holidays/Holidays_ch.xml
Labels: type: enhancement, topic: public holiday, country: switzerland

#708 Replace XML util getMonth with default APIs
  jollyday-jackson/src/main/java/de/focus_shift/jollyday/jackson/JacksonFixed.java
  jollyday-jackson/src/main/java/de/focus_shift/jollyday/jackson/XMLUtil.java
  jollyday-jaxb/src/main/java/de/focus_shift/jollyday/jaxb/JaxbFixed.java
  jollyday-jaxb/src/main/java/de/focus_shift/jollyday/jaxb/XMLUtil.java
Labels: type: enhancement, topic: performance

#709 Rename xmlUtils to (Jackson/Jaxb)XMLMapper
  jollyday-jackson/src/main/java/de/focus_shift/jollyday/jackson/JacksonConfigurationService.java
  jollyday-jackson/src/main/java/de/focus_shift/jollyday/jackson/JacksonXMLMapper.java
  jollyday-jackson/src/test/java/de/focus_shift/jollyday/jackson/test/XMLUtilTest.java
  jollyday-jaxb/src/main/java/de/focus_shift/jollyday/jaxb/JaxbConfigurationService.java
  jollyday-jaxb/src/main/java/de/focus_shift/jollyday/jaxb/JaxbXMLMapper.java
  jollyday-jaxb/src/test/java/de/focus_shift/jollyday/jaxb/test/XMLUtilTest.java
Labels: type: enhancement
