Repository focus-shift/jollyday, pull requests merged in 2024-01, with the labels that each got.

#417 Add missing OSGi SPI headers
  jollyday-core/pom.xml
  jollyday-jackson/pom.xml
  jollyday-jaxb/pom.xml
Labels: type: bug

#418 Upgrade maven wrapper to 3.9.6
  .mvn/wrapper/maven-wrapper.properties
Labels: java, type: dependencies

#421 Fix OSGi bundle not exporting Jackson packages
  jollyday-jackson/pom.xml
Labels: type: bug

#435 Static Jackson mapper creator
  jollyday-jackson/src/main/java/de/focus_shift/jollyday/jackson/XMLUtil.java
Labels: type: bug, topic: jackson, topic: performance

#433 Improve dutch holiday naming
  jollyday-core/src/main/resources/descriptions/holiday_descriptions_nl.properties
  jollyday-core/src/main/resources/holidays/Holidays_nl.xml
  jollyday-tests/src/test/java/de/focus_shift/jollyday/tests/country/HolidayNLTest.java
Labels: type: bug, country: netherlands, topic: i18n

#437 Parameter improvements and tests
  jollyday-core/src/main/java/de/focus_shift/jollyday/core/parameter/BaseManagerParameter.java
  jollyday-core/src/main/java/de/focus_shift/jollyday/core/parameter/CalendarPartManagerParameter.java
  jollyday-core/src/test/java/de/focus_shift/jollyday/core/parameter/BaseManagerParameterTest.java
  jollyday-core/src/test/java/de/focus_shift/jollyday/core/parameter/CalendarPartManagerParameterTest.java
  jollyday-core/src/test/java/de/focus_shift/jollyday/core/parameter/UrlManagerParameterTest.java
Labels: type: enhancement, topic: testing

#438 Static Utils
  jollyday-core/src/main/java/de/focus_shift/jollyday/core/CalendarHierarchy.java
  jollyday-core/src/main/java/de/focus_shift/jollyday/core/Holiday.java
  jollyday-core/src/main/java/de/focus_shift/jollyday/core/HolidayManager.java
  jollyday-core/src/main/java/de/focus_shift/jollyday/core/caching/HolidayManagerValueHandler.java
  jollyday-core/src/main/java/de/focus_shift/jollyday/core/configuration/ClasspathConfigurationProvider.java
  jollyday-core/src/main/java/de/focus_shift/jollyday/core/configuration/ConfigurationProviderManager.java
  jollyday-core/src/main/java/de/focus_shift/jollyday/core/impl/DefaultHolidayManager.java
  jollyday-core/src/main/java/de/focus_shift/jollyday/core/impl/JapaneseHolidayManager.java
  jollyday-core/src/main/java/de/focus_shift/jollyday/core/parameter/CalendarPartManagerParameter.java
  jollyday-core/src/main/java/de/focus_shift/jollyday/core/util/CalendarUtil.java
  jollyday-core/src/main/java/de/focus_shift/jollyday/core/util/ClassLoadingUtil.java
  jollyday-core/src/main/java/de/focus_shift/jollyday/core/util/ResourceUtil.java
  jollyday-core/src/test/java/de/focus_shift/jollyday/core/util/CalendarUtilTest.java
  jollyday-core/src/test/java/de/focus_shift/jollyday/core/util/ClassLoadingUtilTest.java
  jollyday-jackson/src/test/java/de/focus_shift/jollyday/jackson/test/ChristianHolidayParserTest.java
  jollyday-jackson/src/test/java/de/focus_shift/jollyday/jackson/test/EthiopianOrthodoxHolidayParserTest.java
  jollyday-jackson/src/test/java/de/focus_shift/jollyday/jackson/test/FixedParserTest.java
  jollyday-jackson/src/test/java/de/focus_shift/jollyday/jackson/test/FixedWeekdayBetweenFixedParserTest.java
  jollyday-jackson/src/test/java/de/focus_shift/jollyday/jackson/test/FixedWeekdayRelativeToFixedParserTest.java
  jollyday-jackson/src/test/java/de/focus_shift/jollyday/jackson/test/RelativeToEasterSundayParserTest.java
  jollyday-jackson/src/test/java/de/focus_shift/jollyday/jackson/test/RelativeToFixedParserTest.java
  jollyday-jackson/src/test/java/de/focus_shift/jollyday/jackson/test/RelativeToWeekdayInMonthParserTest.java
  jollyday-jaxb/src/main/java/de/focus_shift/jollyday/jaxb/XMLUtil.java
  jollyday-jaxb/src/test/java/de/focus_shift/jollyday/jaxb/test/ChristianHolidayParserTest.java
  jollyday-jaxb/src/test/java/de/focus_shift/jollyday/jaxb/test/EthiopianOrthodoxHolidayParserTest.java
  jollyday-jaxb/src/test/java/de/focus_shift/jollyday/jaxb/test/FixedParserTest.java
  jollyday-jaxb/src/test/java/de/focus_shift/jollyday/jaxb/test/FixedWeekdayBetweenFixedParserTest.java
  jollyday-jaxb/src/test/java/de/focus_shift/jollyday/jaxb/test/FixedWeekdayRelativeToFixedParserTest.java
  jollyday-jaxb/src/test/java/de/focus_shift/jollyday/jaxb/test/RelativeToEasterSundayParserTest.java
  jollyday-jaxb/src/test/java/de/focus_shift/jollyday/jaxb/test/RelativeToFixedParserTest.java
  jollyday-jaxb/src/test/java/de/focus_shift/jollyday/jaxb/test/RelativeToWeekdayInMonthParserTest.java
  jollyday-tests/src/test/java/de/focus_shift/jollyday/tests/HolidayManagerTest.java
  jollyday-tests/src/test/java/de/focus_shift/jollyday/tests/country/AbstractCountryTestBase.java
  jollyday-tests/src/test/java/de/focus_shift/jollyday/tests/country/HolidayAETest.java
  jollyday-tests/src/test/java/de/focus_shift/jollyday/tests/country/HolidayBMTest.java
  jollyday-tests/src/test/java/de/focus_shift/jollyday/tests/country/HolidayDETest.java
  jollyday-tests/src/test/java/de/focus_shift/jollyday/tests/country/HolidayEGTest.java
  jollyday-tests/src/test/java/de/focus_shift/jollyday/tests/country/HolidayHKTest.java
  jollyday-tests/src/test/java/de/focus_shift/jollyday/tests/country/HolidayKYTest.java
  jollyday-tests/src/test/java/de/focus_shift/jollyday/tests/country/HolidayMUTest.java
  jollyday-tests/src/test/java/de/focus_shift/jollyday/tests/country/HolidayNZTest.java
  jollyday-tests/src/test/java/de/focus_shift/jollyday/tests/country/HolidaySGTest.java
  jollyday-tests/src/test/java/de/focus_shift/jollyday/tests/country/HolidayTRTest.java
  jollyday-tests/src/test/java/de/focus_shift/jollyday/tests/country/HolidayVGTest.java
  jollyday-tests/src/test/java/de/focus_shift/jollyday/tests/country/HolidayXKTest.java
Labels: type: enhancement
